db_url = "sqlite:///rtm.db"
db_echo = false
max_dasgoclient = 4
max_xrdadler32 = 10

[voms-proxy]
min_timeleft = 1000
args = [ "-rfc", "-voms", "cms", "-valid", "96:0"]

[rucio-client]
# account = "t3_ch_cern_opendata_local"